# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# Board info
BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM3

# Required paths
ARDUINO_DIR 		= /usr/share/arduino
ARDMK_DIR 			= /usr/share/arduino
AVR_TOOLS_DIR 		= /usr
AVRDUDE_CONF 		= /etc/avrdude.conf
ARDUINO_CORE_PATH 	= /usr/share/arduino/hardware/archlinux-arduino/avr/cores/arduino
BOARDS_TXT 			= /usr/share/arduino/hardware/archlinux-arduino/avr/boards.txt
ARDUINO_VAR_PATH 	= /usr/share/arduino/hardware/archlinux-arduino/avr/variants
BOOTLOADER_PARENT 	= /usr/share/arduino/hardware/archlinux-arduino/avr/bootloaders

# Define this to have less verbose output
ARDUINO_QUIET = 1

include /usr/share/arduino/Arduino.mk